### ISSUE TITLE
Ringtone ver very low

### ISSUE THREAD

**Issue by foss1user** [juha-h/baresip-studio#350] opened 2023-04-07 15:36 UTC
Phone: Fairphone 4
OS: iodeos 4.1
Android: 13
baresip: 53.1.2 (F-Droid)

Issue:
when I receive a call, the phone rings very, very quietly. I can not hear anything when I am outdoors with more noise. Can you please help me?

**Comment by juha-h** [comment] 2023-04-07 15:54
baresip does not control ring volume.  All I can suggest is that you increase Ringtone volume in Android settings.

**Comment by foss1user** [comment] 2023-04-07 16:02
Thak you for your quick reply.

All other ring and notification tones are loud, while at the same time and also the same sound settings on the phone baresip ringtone is very low. Any idea. Note: I am not a tech geek :(

![Screenshot_20230407-165615_Settings](https://user-images.githubusercontent.com/130167358/230639346-fd9d9deb-e5a0-44ea-b1a3-29a5b5ec646b.png)

**Comment by juha-h** [comment] 2023-04-07 16:09
foss1user writes:

> All other ring and notification tones are loud, while at the same time and also the same sound settings on the phone baresip ringtone is very low. Any idea. Note: I am not a tech geek :(

When call is coming in, try in Android settings to increase/decrease
ring volume.  On my Android 13 device, ring volume is
increasing/decreasing. If it does not on yours, try if media or call
volume affects your ring volume.

**Comment by foss1user** [comment] 2023-04-07 16:53
Thank you for your response even in the holiday.

I changed all the tones as high. But nothing has changed.

![Screenshot_20230407-174734_Settings](https://user-images.githubusercontent.com/130167358/230646867-f6490c9e-4c2a-4154-9c00-fc44b00dd9aa.png)

**Comment by juha-h** [comment] 2023-04-08 05:37
I just tested with Pixel 7 emulator and also with that ring volume went up/down when I changed `Ring & notification volume` in settings.  Perhaps the issue is related to your device/OS.  Try with some other device to find out.

**Comment by juha-h** [comment] 2023-04-14 14:42
Closing this because the issue seems to be device specific and I cannot reproduce it on any of my devices nor on Pixel emulators.

**Closed by juha-h** 2023-04-14 14:42 UTC
