### ISSUE TITLE
baresip can't read my phone's contact list

### ISSUE THREAD

**Issue by znoteer** [juha-h/baresip-studio#217] opened 2022-01-26 00:46 UTC
Baresip+ v 26.0.0
CalyxOS 2.11.0 (AOSP android 11)

In my phone's settings I've given baresip+ permission to access my contact list.

Actual result: I can't see my contact list from within baresip+

Expected result: Once the permission is granted, I was expecting either to see my contact list or be presented with a button to go read that contact list.

It isn't practical to have to maintain two contact lists independantly nor to have to go back and forth copying and pasting between contact list and baresip+.

Please consider getting baresip+ to access the contact list once the permission has been granted.

**Comment by juha-h** [comment] 2022-01-26 06:59
znoteer writes:

> In my phone's settings I've given baresip+ permission to access my
> contact list.
> 
> Actual result: I can't see my contact list from within baresip+

That is the currently intended behavior.  It is possible to export
individual baresip contacts to Android contacts, but not access Android
contacts from baresip.  In order to export baresip contacts to Android
contacts, both READ_CONTACTS and WRITE_CONTACTS permissions are needed.

> Expected result: Once the permission is granted, I was expecting
> either to see my contact list or be presented with a button to go read
> that contact list.
> 
> It isn't practical to have to maintain two contact lists independantly
> nor to have to go back and forth copying and pasting between contact
> list and baresip+.

Android contacts are available to all applications to which the
permission is granted and may be also to Google and device vendor.  For
security reasons, I have thus not wanted to encourage baresip users to
use Android contacts.

It is possible to make baresip calls from Android SIP contacts though.

> Please consider getting baresip+ to access the contact list once the
> permission has been granted.

Each baresip contact has a SIP URI.  Android contacts usually have only
a phone number.  If such Android contacts would be made available to
baresip, baresip would not know how to map the phone numbers to SIP URIs
when baresip has more than one account configured.

**Comment by gdt** [comment] 2022-01-26 13:27
I don't think it's reasonable to withhold necessary functionality because some people might make bad decisions.  In my case, I'm running CalyxOS, and my android contacts are on a selfhosted server with DAVx5.   I don't see anything wrong with that.

I also don't follow your logic.   baresip using android contacts that already exist doesn't seem like any incremental harm.  The real harm is someone using a non-degoogled android phone in the first place, and particularly if they store contacts on a Google or other adtech cloud service, and if they install apps that have contact access and exfiltrate them.     If you mean that by making baresip not work with android contacts, this will somehow cause people who would have put their contacts in android contacts to instead not do that, it's hard to conceive on only one person doing that.

In general, I find the permissions/security discussion on Android to be missing the main point which is that while permissions help contain untrustworthy code, the most important thing is to run only trustworthy code (and I put baresip in that category).  So yes, a program that has no logical need for contacts should not read them, but a program that is intended to be used to interact with people in contacts needs to deal with contacts.

**Comment by twisteros** [comment] 2022-01-26 14:12
> Android contacts are available to all applications to which the permission is granted and may be also to Google and device vendor. For security reasons, I have thus not wanted to encourage baresip users to use Android contacts.

I understand your concerns. 
Can we have a tick box in Settings ie. Allow Android contacts.
Once ticked it could bring up a confirmation dialog with a security warning.
Once confirmed Contacts screen would list both Android and app contacts.

**Comment by juha-h** [comment] 2022-01-26 17:36
@gdt @twisteros Good that you opened this discussion on contacts.  I have not found a good and simple solution on how to integrate Android contacts with  baresip contacts.

I myself only use baresip contacts.  One reason is that I have not found on F-Droid a contact app that would support SIP contacts.  See, for example, https://github.com/SimpleMobileTools/Simple-Contacts/issues/670 regarding Simple-Contacts.

If there would be Setting option `Allow Android Contacts` `yes/no` then what would it mean?  Would baresip contacts icon then lead to Android contacts app when the icon touched or when user chooses to add peer's SIP URI to contacts?  Or would Android contacts be merged with baresip contacs each time when baresip  starts or when baresip contacts activity is opened?  What would happen to earlier imported Android contacts that don't exist anymore?  If Android contact only has a phone number and not SIP URI, how would the number be converted to SIP URI?

**Comment by twisteros** [comment] 2022-01-26 22:20
I use a SIP provider which is basically a VOIP gateway to the telephony network.
When I ring a phone number the client app ie. Linphone calls phone_number@provider_address.
From what you're saying I understand you use the app to ring non-telephony addresses ie. aphanumeric_string@provider_address. 

Regarding the "Allow Android Contacts", if it was set to Yes then local baresip contacts would be 
mixed together with device contacts. They would be pulled everytime the Contacts activity got 
launched. If device contacts were fetched just once on the startup we would miss contacts added 
after that time. Only contacts with phone number or SIP URI would be fetched. A contact with both 
values missing is not ring-able (unless I'm missing something). The other way to do it is to grey them 
out so the user knows there is a contact but it misses some information.

_What would happen to earlier imported Android contacts that don't exist anymore?_
I understand you mean the scenario when a contact is added/deleted after the contacts 
activity has been loaded. The contacts activity could listen for changes in Contact Database
and update the list if required.

What could happen when a user tap a contact:
1/ If there is more than one active account a user would need to select an account to make a call.
There could be an option to save the selected account as default for that contact.

2/ check the contact's SIP URI field
If it was filled out then its value would be used. Otherwise the app would use the following 
phone_number@selected_account_provider_address

**Comment by gdt** [comment] 2022-01-27 00:30
@juha-h Thanks for the comments.  I agree this is really difficult and was mostly objecting to the notion that it was somehow dangerous.

Agreed with @twisteros that SIP addresses of number@provider is a very important use case, for gateway providers, and for  self-hosted asterisk with a PSTN port.  There, I want the address recognized as a gateway address and looked up as a regular E.164 number, to display name/picture from my (Android) contacts.

I basically view it as a bug in the Android world that there even needs to be a concept of a contacts database inside baresip.  But it does seem to be a bug, so it's a good question how to deal.  As a datapoint, the contacts app in CalyxOS (which is I'm pretty sure from AOSP) has a SIP field, but it's a single field.  Arguably it should either allow URIs in phone fields (with a default/implicit tel:) or SIP should be like phone, multiple and work/home.  That SIP field shows up as "internet communications" in Thunderbird (via DAVx5 and a carddav server), with the other choice there being jabber.

I put in a sip address for myself, and when I touch it in contacts, I get a prompt asking me to choose an app to complete the call, baresip+, linphone and "call management".   So that part seems working.

One idea is to use Android contacts, and to have baresip basically the equivalent of lisp properties where the SIP addresses that should be storable in the contact can be stored, as a sort of sidecar mapping from each contact.   The user would perhaps perceive this, but it would mean that there is a single notion of contacts, with baresip keeping the properties that really should be in contacts but aren't.   If you delete a contact from contacts, that should delete the extra SIP info too, as if it were part.  This means that if you add a contact in baresip the name should go in the android database and the SIP info kept on the side.

A further possibility is if the Android contacts database (vs app) can handle richer SIP, to store things there, and have a UI to see it, but not actually keep data in a private baresip database. 

The CalyxOS contacts app also manages to show Signal as an option to dial a PSTN number but that may be a CalyxOS enhancement.   I think it should be possible for baresip, if it is told that i can dial PSTN numbers via a gateway, to register as a handler.

(Hope this helps; I am still in the state of getting my home SIP stuff in order and not an active user.)

**Comment by juha-h** [comment] 2022-01-27 16:54
Implementing all what has been proposed is not trivial and my resourced are limited.  So would it be OK to start with what I proposed here https://github.com/juha-h/baresip-studio/issues/218#issuecomment-1023427180?  The next step would then be merge of Android contacts.

**Comment by gdt** [comment] 2022-01-27 16:57
It's your time and your call.  I am just trying to sketch out design/architecture thoughts in the hope that it would be useful.

I think adding the #218 support would make baresip useful for another significant situation, and it seems much lower effort, so I think it's wise to do that first.

**Comment by znoteer** [comment] 2022-01-27 20:16
I agree with @gdt.  baresip is your baby. I'll let you decide what to implement, and when and how to do it.  I'm just making suggestions that would be useful to me while thinking they would be useful to others as well.  Your proposal in issue 218 sounds like as good a place to start as any.  Good luck, and thanks once again.

**Comment by juha-h** [comment] 2022-01-28 12:27
I made some tests by initiating telephone number calls from Google Contacts app.  The app gave them to baresip as tel: URIs, for example
```
android.intent.action.CALL tel:%2B358%2040%203640234
```
This makes sense to me.  So the first step would be allow baresip "Call to ..." field to contain tel: URI.  Same for contact URI.  When telephone number contacts are imported from Android to baresip, they would thus be tel: URIs

The next step would be to figure out, what to do when call to tel: URI is made.  Some operators may accept tel: URIs as Request-URIs.  Some others may require them to be converted to sip: URIs.

**Comment by juha-h** [comment] 2022-02-02 17:14
I have implemented possibility to store in contact either a SIP URI or tel URI.  As before Contact can have only one URI, which has the advantage that the contact can be called directly from contact list w/o need to first open the contact.  I could later try to allow more URIs in one Contact.  Then touching a contact in the list would open a new activity where the URI can be chosen.

I also added Telephony Provider (SIP URI hostpart) item to account configuration.  That is used in tel2sip mapping when telephone number is called from the account.  Telephony Provider defaults to account's domain part. If is set to empty, then telephone numbers cannot be called from the account.

Regarding choosing which account to use to call a Contact, the account to be used still is the one that was the selected one when Contacts activity was entered.  It would be inconvenient if the user each time would be prompted to select, which account to use. I could later think about possibility to associate a contact with default account, but that too would need some mechanism to override the default.

Regarding importing Android contacts, it would be easier to do if a single baresip contact could have multiple SIP/tel URIs.  But it would still be quite an undertaking.  For example, if baresip and Android both have a contact with the same name, then also their URIs would need to be merged. But I don't have resources to develop inside baresip a full blown contacts application.  If someone prefers to use Android contacts, it always possible to initiate baresip calls from there.  I'll investigate if sending of messages could also be supported.

**Comment by juha-h** [comment] 2022-02-10 07:31
I added new entry to feature requests regarding this issue: https://github.com/juha-h/baresip-studio/wiki/Feature-Requests.  I'll close this issue now, but new comments are of course welcome here even when it is closed.  If needed, I'll then update the feature request.

**Comment by znoteer** [comment] 2022-02-12 14:26
Thanks.  I look forward to the feature!

**Comment by juha-h** [comment] 2022-02-14 09:09
Version 41.0.0 of baresip and 28.0.0 of baresip+ now allow user to choose between baresip contacts and Android contacts. Preference can be configured in Settings.  No effort has been made to integrate baresip contacts and Android contacts or make baresip an Android contacts app.

**Comment by twisteros** [comment] 2022-02-16 08:56
Great job! Looking forward to see that version in F-Droid.

**Comment by znoteer** [comment] 2022-02-19 20:56
Awesome! I can't wait for it to appear in the repos.  Thank you.

**Comment by juha-h** [comment] 2022-02-22 12:52
@znoteer @gdt @twisteros 
Versions 42.2.0 and 29.2.0 (+) that are now available in Google Play and should become available in F-Droid in a couple of days include some new contact related feature.

User can now choose in Settings if he/she wants to use baresip contacts, Android contacts, or both.  If both is chosen and both baresip contacts and Android contacts include the same contact name, baresip contact is used.

New Android contacts can be added and existing ones can be deleted, but there is no possibility to modify Android contacts.  This is because Android contacts can include all kinds of fields and baresip is not a contact app.

When user starts typing in call or transfer URI field, drop down list of matching contact names shows up like before.  However, only those Android contact names are included in the list that have exactly one (tel or SIP) URI.  That is because the URI that will be called needs to be unambiguous.

Comments are welcome.

**Comment by juha-h** [comment] 2022-05-09 05:45
@znoteer @twisteros @gdt After adding possibility to use Android contacts, Google does not anymore accept baresip+ in Play store.  They claim that baresip+ "uploads users' Contact List information without posting a valid privacy policy".  baresip+ does not upload Contact List information anywhere and does post privacy policy if user decides to use Android contacts.

I have asked more information from Google, but got reply "As much as I'd like to help, unfortunately I’m not able to provide any more detail or a better answer to your question.".  So I have no other choice that to remove baresip+ from the dictator's Play Store.  Use F-Droid instead.

**Closed** 2022-05-09 05:45 UTC

**Comment by gdt** [comment] 2022-05-09 11:35
@juha-h Thank you for taking the high road with the Play Store.  I am always saddened when I see Free Software that behaves reasonably torque itself around in response to arbitrary and capricious behavior. 

And no practical concerns on my end -- I have never used the Play Store, only F-Droid, from day 1 of my android experience.

**Comment by znoteer** [comment] 2022-05-09 13:50
Thanks for the update.  I'm already using F-Droid, so I'm good.

**Comment by juha-h** [comment] 2022-05-11 18:48
Just to update, today latest version of baresip+ appeared in Play store, even when I didn't make any changes regarding contacts or app's privacy policy.  So looks like the algorithms Google uses to detect malware have quite serious bugs in them.

**Comment by ddevz** [comment] 2025-03-09 22:40
> It is possible to make baresip calls from Android SIP contacts though.

Can you clarify that?  Do you mean we (as users) should be able to install baresip, then go into Android contacts, tap a a SIP phone number and it should jump to baresip?  (I just tried and that does not work for me).   Or are you perhaps saying that from a API perspective that it's possible for a programmer do such a thing, but baresip has not done so?

**Comment by juha-h** [comment] 2025-03-10 01:27
It should be possible to use baresip from any contact app if you define baresip as the default phone app.  If you don't want to do that, when it is possible to access Android contacts from baresip Contacts.
