### ISSUE TITLE
Password not remembered

### ISSUE THREAD

**Issue by wandhydrant** [juha-h/baresip-studio#85] opened 2020-06-07 21:30 UTC
Hello,
whenever I quit or restart the application, I'm asked again the password. My password is very long and complicated :-)  I guess that usually the password gets remembered?

This is on a fresh Android 10, where I tried to deactivate as many Google services as possible. Maybe I deactivated one too many?

I tried "logcat | grep -i baresip" in debug mode but nothing showed up.

Thank you very much for your work!

**Comment by wandhydrant** [comment] 2020-06-07 21:43
This happened only in the presence of an account that was not yet well configured. (Though it did seem to me that the account I was asked for was the default account, which was well configured.) I threw all accounts out, and started with a single one - now the password gets remembered.

**Comment by juha-h** [comment] 2020-06-08 07:00
wandhydrant writes:

> whenever I quit or restart the application, I'm asked again the
> password. My password is very long and complicated :-)  I guess that
> usually the password gets remembered?

Yes, as long as you return from Account configuration with OK (v) button
and not with back (<-) button.

**Comment by juha-h** [comment] 2020-06-08 07:11
Password should be asked when baresip is started only if Authentication Username is given in account's configuration, but Authentication Password is not given.

I added a couple of new accounts, but could not reproduce this.  Perhaps by accident you returned from account's  configuration with back (<-) button.

I'll close this now, but please reopen if it happens again and tell the step you took.

**Closed by juha-h** 2020-06-08 07:11 UTC
