### ISSUE TITLE
baresip prevents screen locking

### ISSUE THREAD

**Issue by adatum** [juha-h/baresip-studio#126] opened 2020-12-12 21:15 UTC
Is it expected that having the baresip app on screen prevents the screen from locking? The screen still dims and turns off after a delay or by pressing the power button, but upon waking the screen, it is not locked and still showing baresip's screen.

**Comment by juha-h** [comment] 2020-12-13 09:21
That is intended behavior, since it allows answering or rejecting a call when waking the screen to main activity.

**Comment by adatum** [comment] 2020-12-13 09:36
> answering or rejecting a call when waking the screen to main activity.

I'm not sure I understand. What is waking the screen? Why would anyone want the screen not to lock after it has turned off?

Regarding answering or rejecting calls, under "normal" conditions (screen off, baresip running with icon in taskbar, but main activity screen of baresip not open), upon receiving a call the phone rings, but the screen does not turn on, and after manually waking the screen there is just a notification about the incoming call which requires unlocking the screen to then accept or reject the call. Is this intended as well? 

I would expect an incoming call to wake the screen and display caller ID/number, with an option to accept or reject the call bypassing the lock screen, i.e. no need to unlock to accept or reject the call.

**Comment by juha-h** [comment] 2020-12-13 10:48
When screen is locked and call comes in, I can answer it from the notification without opening the app.  But since baresip app screen is shown, I can also hangup the call without first dismissing the keyguard using a pin or by some other means.  It would not be convenient if I could not hangup the call without first manually dismissing the keyguard.

I just checked and the behavior is the same when PSTN call comes in and my phone is locked.  The PSTN phone app screen shows up without me having to first manually dismiss the keyguard.

Perhaps I'm not understanding your concern?

**Comment by adatum** [comment] 2020-12-13 21:34
> I can answer it from the notification without opening the app.

Hmm... I can't. 

For me, an incoming call does not wake the screen, so I can only hear the ringing. To see the call notification I have to manually wake the screen. If I double tap the notification to try to answer the call, I need to first unlock the screen using a swipe, pin, or pattern. This then opens baresip's main screen where I can accept or reject the call. 

Effectively the notification is just a notification and offers no call function. All call operations are done only through the app screens. This is too lengthy to be practical. 

The PSTN call behavior you describe is what I would expect.

**Comment by juha-h** [comment] 2020-12-14 08:48
I just made a test:

- started baresip and it registered an account
- pressed back button to get back to device's main screen
- cleared all apps
- locked the device by pressing power button
- called the account from another device
- a notification showed up with Accept/Reject choices
- I chose Accept
- baresip main window became visible
- I closed the call

This worked on both of my Android One devices (Android 9 and Android 10).

I don't have access to a device with API level < 27 (Android < 8.1.0) where `requestDismissKeyguard` function is not available yet and this may not work at all:

```
        if (Build.VERSION.SDK_INT >= 27) {
            setShowWhenLocked(true)
            setTurnScreenOn(true)
            kgm.requestDismissKeyguard(this, null)
        } else {
            window.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
                    WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
                    WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD)
        }
    }
```

**Comment by adatum** [comment] 2020-12-15 08:31
The behavior you describe makes sense, but it's not what happens on my phone, as mentioned. Maybe it's specific to my setup. I'm running an e-OS custom ROM, based on Lineage OS, based on Android 9.

**Comment by juha-h** [comment] 2020-12-18 12:26
I'll close this, since I cannot reproduce it on my Android One devices (Android versions 9 and 10).  Perhaps the issue is vendor and/or Android version specific.

**Closed by juha-h** 2020-12-18 12:26 UTC
