### ISSUE TITLE
when building baresip libraries getting error in linux

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#337] opened 2023-03-21 07:32 UTC
when i am trying to build and install the baresip libraries in linux (MX linux) I am getting this error 

(https://user-images.githubusercontent.com/123717548/226540815-3111696e-9238-4701-b243-df3034d97d55.PNG)

plz help me to build baresip in android studio properly i would like to customize the baresip app to my needs

I have completed step - 3 successfully means getting the list of libraries when entering this command (make download-sources) except rem file rest of the files i am getting with the libraries but when i am entering last command make install-all i am getting this error after executing.

This is my makefile after editing the file 

(https://user-images.githubusercontent.com/123717548/226541998-b456b24d-acf7-4cd3-992c-ef44ea7d2711.PNG)
Is this correct? I think it is but I am not sure about that.

This is my overall scenario

Thanks

**Comment by juha-h** [comment] 2023-03-21 10:23
Make sure that you have latest master of libbaresip-android project and have downloaded latest openssl, re and baresip as described in Makefile. Then make install openssl followed by libbaresip.

**Comment by AviWA** [comment] 2023-03-21 10:45
Of course I am using the latest versions of all but still i am getting errors.

**Comment by AviWA** [comment] 2023-03-21 10:47
Is my edited makefile is correct? I have a doubt on that

**Comment by juha-h** [comment] 2023-03-21 14:45
I cannot reproduce this.  Also F-Droid build has worked fine.

cd re && \
rm -rf build && rm -rf .cache && mkdir build && cd build && \
cmake .. \
	-DANDROID=ON -DANDROID_PLATFORM=21 -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_TOOLCHAIN_FILE=/opt/Android/ndk/25.1.8937393/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 -DCMAKE_ANDROID_ARCH_ABI=x86_64 -DCMAKE_SKIP_INSTALL_RPATH=ON -DCMAKE_C_COMPILER=x86_64-linux-android21-clang -DCMAKE_CXX_COMPILER=x86_64-linux-android21-clang++ -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_FIND_ROOT_PATH="/opt/Android/ndk/25.1.8937393;/usr/src/libbaresip-android/openssl" \
	-DOPENSSL_VERSION_MAJOR=3 \
	-DOPENSSL_ROOT_DIR=/usr/src/libbaresip-android/openssl && \
cmake --build . --target re -j
-- The C compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/Android/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_WATOMIC
-- Performing Test COMPILER_SUPPORTS_WATOMIC - Success
-- Looking for backtrace
-- Looking for backtrace - not found
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY) 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found ZLIB: /opt/Android/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/21/libz.so (found version "1.2.12") 
-- Found OpenSSL: /usr/src/libbaresip-android/openssl/libcrypto.a (found suitable version "3.1.0", minimum required is "1.1.0")  
-- Looking for arc4random
-- Looking for arc4random - found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for res_ninit
-- Looking for res_ninit - not found
-- Looking for thrd_create
-- Looking for thrd_create - not found
-- Looking for accept4
-- Looking for accept4 - found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - found
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/libbaresip-android/re/build
gmake[1]: Entering directory '/usr/src/libbaresip-android/re/build'
gmake[2]: Entering directory '/usr/src/libbaresip-android/re/build'
gmake[3]: Entering directory '/usr/src/libbaresip-android/re/build'
gmake[4]: Entering directory '/usr/src/libbaresip-android/re/build'
gmake[4]: Leaving directory '/usr/src/libbaresip-android/re/build'
gmake[4]: Entering directory '/usr/src/libbaresip-android/re/build'
[  1%] Building C object CMakeFiles/re-objs.dir/src/av1/depack.c.o
...
[ 13%] Building C object CMakeFiles/re-objs.dir/src/hmac/hmac_sha1.c.o
[ 13%] Building C object CMakeFiles/re-objs.dir/src/http/auth.c.o
...

**Comment by juha-h** [comment] 2023-03-22 09:45
Turn verbose libre.a build on and check if your openssl include matches your setup:
```
/usr/src/libbaresip-android$ git diff
diff --git a/Makefile b/Makefile
index fdc32c9..ccf922f 100644
--- a/Makefile
+++ b/Makefile
@@ -299,7 +299,7 @@ libre.a: Makefile
        -DCMAKE_FIND_ROOT_PATH="$(NDK_PATH);$(PWD)/openssl" \
        -DOPENSSL_VERSION_MAJOR=3 \
        -DOPENSSL_ROOT_DIR=$(PWD)/openssl && \
-   cmake --build . --target re -j
+   VERBOSE=1 cmake --build . --target re -j
 
 libbaresip: Makefile openssl opus amr spandsp g7221 g729 webrtc gzrtp sndfile libre.a
    cd baresip && \

```

**Comment by juha-h** [comment] 2023-03-22 15:44
I'll close this since this is not an issue with baresip-studio project.  It belongs to libbaresip-android project, but as I have written, I cannot reproduce it and also F-Droid build of  libbaresip-android has worked fine.

**Closed by juha-h** 2023-03-22 15:44 UTC
