### ISSUE TITLE
Too quiet audio

### ISSUE THREAD

**Issue by toby63** [juha-h/baresip-studio#393] opened 2023-07-07 22:47 UTC
I use baresip+ Version 44.1.1 from F-Droid on Android 12.

There are two problems though:
1. The audio output is too quiet, it seems that #186 is related to this.
   I was able to mitigate the problem by increasing the "media volume" to maximum, but first of all I think the "call volume" should be used instead of the media volume (because the media volume is set lower for a reason, at least in my case) and secondly the sound is still a bit too quiet on maximum.

2. The audio input is also too quiet and barely hearable.
     I couldn't find an option to increase the microphone volume.

Both problems don't exist on many other Apps that I use, so the problem seems to be on the side of this app.
Maybe you could take at look at how other (Open Source) Apps solve this.

**Comment by juha-h** [comment] 2023-07-08 16:21
You can set in Audio Setting the Default Call Volume that you want to use for baresip.  The setting does not affect other applications.  I have tested with several Android devices and media volume is OK for baresip calls with Default Call Volume value 7.  What brand is your device?  Are you using Android OS provided by the device vendor?

baresip app does not select which volume (call or media) is used.   Audio mode is set to MODE_IN_COMMUNICATION, when call is established.  If I remember correctly, also for example in linphone call volume is controlled by media volume setting.

What comes to audio input, Android operating system API does not have any means to set microphone gain.

There is difference between baresip app and linphone app how audio focus is requested for call.  In baresip this is done
```
val attributes = AudioAttributesCompat.Builder()
                .setUsage(AudioAttributesCompat.USAGE_MEDIA)
                .setContentType(AudioAttributesCompat.CONTENT_TYPE_SPEECH)
                .build()
```

and in linphone this is done:
```
        AudioAttributesCompat audioAttrs = new AudioAttributesCompat.Builder()
            .setUsage(AudioAttributesCompat.USAGE_VOICE_COMMUNICATION)
            .setContentType(AudioAttributesCompat.CONTENT_TYPE_SPEECH)
            .build();
```
I don't anymore remember what was the reason for USAGE_MEDIA.  If you want to test, I could create an APK where 
USAGE_VOICE_COMMUNICATION is requested.

**Comment by toby63** [comment] 2023-07-08 21:47
> You can set in Audio Setting the Default Call Volume that you want to use for baresip. The setting does not affect other applications. I have tested with several Android devices and media volume is OK for baresip calls with Default Call Volume value 7.

I already set it to 10 and it is still a bit too quiet.
But I will also try it with 7.

>  What brand is your device? Are you using Android OS provided by the device vendor?

I have a custom vendor-provided version of AOSP (Open Source Android).
I know this is not perfect, but still everything is working normal in other apps, so I don't think this has much to do with it.
The only significant difference that I can think of would be, that Google Services are replaced by other ones, such as MicroG e.g.
 
> baresip app does not select which volume (call or media) is used. Audio mode is set to MODE_IN_COMMUNICATION, when call is established. If I remember correctly, also for example in linphone call volume is controlled by media volume setting.

Interesting.

> What comes to audio input, Android operating system API does not have any means to set microphone gain.

Thats very unfortunate. Still other apps have normal loudness.

> There is difference between baresip app and linphone app how audio focus is requested for call. In baresip this is done
> 
> ```
> val attributes = AudioAttributesCompat.Builder()
>                 .setUsage(AudioAttributesCompat.USAGE_MEDIA)
>                 .setContentType(AudioAttributesCompat.CONTENT_TYPE_SPEECH)
>                 .build()
> ```
> 
> and in linphone this is done:
> 
> ```
>         AudioAttributesCompat audioAttrs = new AudioAttributesCompat.Builder()
>             .setUsage(AudioAttributesCompat.USAGE_VOICE_COMMUNICATION)
>             .setContentType(AudioAttributesCompat.CONTENT_TYPE_SPEECH)
>             .build();
> ```
> 
> I don't anymore remember what was the reason for USAGE_MEDIA. If you want to test, I could create an APK where USAGE_VOICE_COMMUNICATION is requested.

That would be very nice.
Do you think this could maybe also change how Android or some other software in between or within your app handle things?
Like filters, gain, compressors or something like that?

**Comment by juha-h** [comment] 2023-07-09 06:12
Try with https://box.tutpro.com/tmp/baresip+.apk.  It requests audio focus for voice communication.  Is call volume audio now used instead of media volume?  Did it have any effect on this issue?

**Comment by toby63** [comment] 2023-07-13 20:36
Sry for the delay, I tried your apk now.
Somehow it seems that the App is still using media volume, the UI shows a musical note.

But now the audio is slightly better, testing with the test call contact, I could now hear the contacts voice and my recorded voice more clearly.
I know this sounds odd maybe, but that is my perception.

**Comment by juha-h** [comment] 2023-07-15 14:26
According to https://developer.android.com/guide/topics/media-apps/volume-and-earphones

`Unless your app is an alarm clock, you should play audio with usage [AudioAttributes.USAGE_MEDIA](https://developer.android.com/reference/android/media/AudioAttributes#USAGE_MEDIA).`

So I would prefer to leave output volume control as it currently is.

Regarding `Too quiet audio`, can you try with a device running non-AOSP Android?  There has been several issues related to AOSP and this can be one of them.

**Comment by toby63** [comment] 2023-07-19 19:35
> can you try with a device running non-AOSP Android? There has been several issues related to AOSP and this can be one of them.

Sry, but no.

**Comment by juha-h** [comment] 2023-07-24 14:53
I cannot reproduce this on my Android devices and as I already mentioned, there is no way in Android API to control microphone gain.  I did change audio focus request for USAGE_VOICE_COMMUNICATION in case that makes any difference.  Call volume is still controlled by media.

I'll close this since I cannot figure out anything else that I could do.  I suspect that this is an AOSP related issue.

**Closed by juha-h** 2023-07-24 14:53 UTC

**Comment by juha-h** [comment] 2023-08-17 07:16
The issue with low microphone gain has only appeared with devices running AOSP.  I suggest you discuss the issue in some AOSP forum.
