### ISSUE TITLE
Unable to register to IPv6 server

### ISSUE THREAD

**Issue by nivex** [juha-h/baresip-studio#56] opened 2019-10-25 13:57 UTC
Using version 11.2.0 from F-Droid on Android version 5.1

Steps to reproduce:
- Create new account: user@pbx.home.nivex.net
- Set Authentication password
- Check the "Register" box
- Tap confirm (checkmark in upper right)

Expected result:
- Registration to server

Actual result:
- Error message displayed:
Registering of `sip:user@pbx.home.nivex.net` failed.: Protocol not supported

**Comment by juha-h** [comment] 2019-10-25 15:02
Unfortunately my mobile operator does not provide me IPv6 address and it is hard for me to test this.
If might help if you could share NAPTR/SRV/IP address query results on the domain.  Also, you could try by checking 'Prefer IPv6' in the Settings unless you already did it.  And if you can, show what 'adb logcat | grep Baresip' gives when you try to register the account.

**Comment by nivex** [comment] 2019-10-25 15:17
This is with 'Prefer IPv6' checked. I get a different error with it unchecked.

There are no NAPTR or SRV records for this host.
```
kjotte@daedalus:~$ dig +noall +answer -t AAAA pbx.home.nivex.net
pbx.home.nivex.net.	2989	IN	CNAME	avalon.home.nivex.net.
avalon.home.nivex.net.	2989	IN	AAAA	2606:a000:a442:9800:5054:ff:fe26:4df6
```

Logs:
```
kjotte@daedalus:~$ adb logcat | grep Baresip
D/Baresip Service( 3855): Network '314' is available
D/Baresip Lib( 3855): setting dns servers '[fd60:e0:a0f4:321::4]:53,[fd60:e0:a0f4:121::10]:53,172.31.3.30:53'
D/Baresip Lib( 3855): net_dns_debug_log
D/Baresip Lib( 3855):  DNS Servers from Config: (3)
D/Baresip Lib( 3855):    0: [fd60:e0:a0f4:321::4]:53
D/Baresip Lib( 3855):    1: [fd60:e0:a0f4:121::10]:53
D/Baresip Lib( 3855):    2: 172.31.3.30:53
D/Baresip Lib( 3855): 
D/Baresip Lib( 3855): ua event (REGISTERING) 
D/Baresip Lib( 3855): sending ua/call 3094009792/0 event registering
D/Baresip Service( 3855): uaEvent got event registering/3094009792/0
D/Baresip Lib( 3855): ua event (REGISTER_FAIL) Protocol not supported
D/Baresip Lib( 3855): sending ua/call 3094009792/0 event registering failed,Protocol not supported
D/Baresip Service( 3855): uaEvent got event registering failed,Protocol not supported/3094009792/0
D/Baresip Lib( 3855): ua: SIP register failed: Protocol not supported
D/Baresip ( 3855): Failed to register sip:aurora@pbx.home.nivex.net
```

**Comment by juha-h** [comment] 2019-10-25 15:27
Just to rule out issues with dynamic DNS server setup, try if it helps when you manually give the IPv6 addresses of the two DNS servers in Settings:
```
DNS Servers
[fd60:e0:a0f4:321::4]:53,[fd60:e0:a0f4:121::10]:53
```

**Comment by juha-h** [comment] 2019-10-25 16:44
And if that doesn't help, then in Account config, set Outbound Proxy like this:
```
sip:[2606:a000:a442:9800:5054:ff:fe26:4df6]:<port>;transport=<proto>
```
Click Outbound Proxies title for help.

**Comment by nivex** [comment] 2019-10-25 17:59
Manually set the DNS servers in Settings as recommended. No change in behavior.

Set Outbound Proxy as recommended. No change in behavior.
```
D/Baresip (22609): New outbound proxies are [sip:[2606:a000:a442:9800:5054:ff:fe26:4df6]:5060;transport=udp]
D/Baresip Lib(22609): updating account of ua 3094403904
D/Baresip Lib(22609): ua event (REGISTERING) 
D/Baresip Lib(22609): sending ua/call 3094403904/0 event registering
D/Baresip Service(22609): uaEvent got event registering/3094403904/0
D/Baresip Lib(22609): ua: SIP register failed: Protocol not supported
D/Baresip Lib(22609): ua event (REGISTER_FAIL) Protocol not supported
D/Baresip Lib(22609): sending ua/call 3094403904/0 event registering failed,Protocol not supported
D/Baresip Service(22609): uaEvent got event registering failed,Protocol not supported/3094403904/0
D/Baresip (22609): Handling service event 'registering failed' for 3094403904
```

**Comment by nivex** [comment] 2019-10-25 18:03
The library does not appear to be detecting the IPv6 address of the device:
```
D/Baresip Lib(23573): --- Network debug ---
D/Baresip Lib(23573):  Preferred AF:  AF_INET6
D/Baresip Lib(23573):  Local IPv4:  wlan0|172.31.3.28
D/Baresip Lib(23573):  Local IPv6:  (not set)
D/Baresip Lib(23573):  Domain: 
D/Baresip Lib(23573): net interfaces:
D/Baresip Lib(23573):          lo:  127.0.0.1
D/Baresip Lib(23573):       wlan0:  172.31.3.28
D/Baresip Lib(23573): net routes:
D/Baresip Lib(23573):  Destination                                 Next Hop                                 Iface           Type
D/Baresip Lib(23573):  0.0.0.0/0                                   172.31.3.1                               wlan0           
D/Baresip Lib(23573):  172.31.3.0/24                               ?                                        wlan0           
D/Baresip Lib(23573):  DNS Servers from System: (3)
D/Baresip Lib(23573):    0: [fd60:e0:a0f4:321::4]:53
D/Baresip Lib(23573):    1: [fd60:e0:a0f4:121::10]:53
D/Baresip Lib(23573):    2: 172.31.3.30:53
D/Baresip Lib(23573): 
D/Baresip Lib(23573): sip:aurora@pbx.home.nivex.net              zzz 
D/Baresip Lib(23573): 
D/Baresip Lib(23573): running main loop ...
```

**Comment by juha-h** [comment] 2019-10-25 18:06
Kevin Otte writes:

> Manually set the DNS servers in Settings as recommended. No change in
> behavior.
> 
> Set Outbound Proxy as recommended. No change in behavior.

OK, thanks for testing.

I checked and IPv6 is enabled when libre and libbaresip are built.  I'll
ask libre/libbaresip folks, what might be the cause "protocol not
supported" error.

**Comment by juha-h** [comment] 2019-10-25 18:12
Sorry, I didn't notice you latest comment until now.  Not having local IPv6 surely will cause the "protocol not supported" error.

Check with 'adb shell ip addr', what does is tell about IP interfaces of the device.

**Comment by juha-h** [comment] 2019-10-25 18:21
You could also try what happens when you set Listen Address as
```
[::]:5060
```
and Bind Address as what 'adb shell ip addr' tells the non-link local IPv6 address of the device is.

**Comment by nivex** [comment] 2019-10-25 18:33
Device definitely has an IPv6 address:
```
kjotte@daedalus:~$ adb shell ip addr show dev wlan0
28: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 100
    link/ether e8:91:20:90:dd:04 brd ff:ff:ff:ff:ff:ff
    inet 172.31.3.28/24 brd 172.31.3.255 scope global wlan0
    inet6 2606:a000:a442:9800:11dc:2fff:1b20:1987/64 scope global temporary dynamic 
       valid_lft 554977sec preferred_lft 52592sec
    inet6 2606:a000:a442:9800:ea91:20ff:fe90:dd04/64 scope global dynamic 
       valid_lft 554977sec preferred_lft 554977sec
    inet6 fe80::ea91:20ff:fe90:dd04/64 scope link 
       valid_lft forever preferred_lft forever
```

Set the Listen Address and Bind address as suggested and it registers.

```
D/Baresip Lib(25413): --- Network debug ---
D/Baresip Lib(25413):  Preferred AF:  AF_INET6
D/Baresip Lib(25413):  Local IPv4:  (not set)
D/Baresip Lib(25413):  Local IPv6:  ???|2606:a000:a442:9800:ea91:20ff:fe90:dd04
D/Baresip Lib(25413):  Domain: 
D/Baresip Lib(25413): net interfaces:
D/Baresip Lib(25413):          lo:  127.0.0.1
D/Baresip Lib(25413):       wlan0:  172.31.3.28
D/Baresip Lib(25413): net routes:
D/Baresip Lib(25413):  Destination                                 Next Hop                                 Iface           Type
D/Baresip Lib(25413):  0.0.0.0/0                                   172.31.3.1                               wlan0           
D/Baresip Lib(25413):  172.31.3.0/24                               ?                                        wlan0           
D/Baresip Lib(25413):  DNS Servers from System: (3)
D/Baresip Lib(25413):    0: [fd60:e0:a0f4:321::4]:53
D/Baresip Lib(25413):    1: [fd60:e0:a0f4:121::10]:53
D/Baresip Lib(25413):    2: 172.31.3.30:53
D/Baresip Lib(25413): 
D/Baresip Lib(25413): sip:aurora@pbx.home.nivex.net              zzz 
D/Baresip Lib(25413): 
D/Baresip Lib(25413): running main loop ...
D/Baresip Lib(25413): aurora@pbx.home.nivex.net: {1/UDP/v6} 200 OK (Asterisk PBX 16.2.1~dfsg-1+deb10u1) [1 binding]
D/Baresip Lib(25413): ua event (REGISTER_OK) 200 OK
D/Baresip Lib(25413): sending ua/call 3093923688/0 event registered
D/Baresip Service(25413): uaEvent got event registered/3093923688/0
D/Baresip (25413): Handling service event 'ua added' for 3093923688
D/Baresip (25413): Handling service event 'registered' for 3093923688
```

It looks like the problem to solve is why it's not detecting the IPv6 address automatically.

**Comment by juha-h** [comment] 2019-10-25 18:39
Kevin Otte writes:

> Device definitely has an IPv6 address:

OK.

> Set the Listen Address and Bind address as suggested and it registers.

Would it register, if you only set Listen Address and leave Bind
Address blank?

> It looks like the problem to solve is why it's not detecting the IPv6
> address automatically.

Exactly.  Thanks for testing.

**Comment by nivex** [comment] 2019-10-25 18:42
> Would it register, if you only set Listen Address and leave Bind Address blank?

Sadly it does not. With Listen Address set and Bind Address blank I still get `Local IPv6:  (not set)` from network debug.

**Comment by juha-h** [comment] 2019-10-25 18:48
Kevin Otte writes:

> Sadly it does not. With Listen Address set and Bind Address blank I
> still get `Local IPv6:  (not set)` from network debug.

How about setting Bind Address and leaving Listen Address empty?

**Comment by nivex** [comment] 2019-10-25 18:55
> How about setting Bind Address and leaving Listen Address empty?

This combination works. Registers and can make calls.

**Comment by juha-h** [comment] 2019-10-25 19:09
As you can see in above, I created an issue about this to baresip git.  Let's wait what the response is.
In the meanwhile, keep Bind Address set.  Thanks for the report.

**Comment by nivex** [comment] 2019-10-25 19:15
Keeping the Bind Address set will work while I'm in one location, but doesn't work when I move networks. Here's hoping they have some ideas. Don't know if it's helpful, but I run baresip on a laptop under Ubuntu and it works fine.

**Comment by gdt** [comment] 2019-10-25 23:54
This seems like it might be related to the source address selection issues.  It seems to me that baresip-android (perhaps inherited from baresip lib) has a notion of figuring out which interface to use globally for baresip and then using that interface's address.  It seems that instead each connection should be allowed to use the routing table and have the OS choose a source address, which might be a different interface, and would be v6 for a v6 destination.  (More later when I test the new bind feature).

It would be interesting for @nivex  to try linphone and see how that goes.

**Comment by nivex** [comment] 2019-10-25 23:59
Linphone 4.0.1 works great. 4.1.1 has a [regression](https://github.com/BelledonneCommunications/linphone-android/issues/677) (likely not related to this issue) that has caused me to go looking for another client.

**Comment by juha-h** [comment] 2019-10-26 07:35
Kevin Otte writes:

> > How about setting Bind Address and leaving Listen Address empty?
> 
> This combination works. Registers and can make calls.

Did you use IPv6 address or interface name (wlan0) as Bind Address?

If address, could you, please, also try with interface name.  If you do
that, what does Network Debug tell Local IPv6 is?

**Comment by juha-h** [comment] 2019-10-26 07:55
It is possible for Android app to be notified about default network
changes:

[https://developer.android.com/reference/android/net/ConnectivityManager.html#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)](url)

Based on that info, it might then be possible to change baresip
bind_address on the fly.

**Comment by nivex** [comment] 2019-10-26 14:58
> Did you use IPv6 address or interface name (wlan0) as Bind Address? If address, could you, please, also try with interface name. If you do that, what does Network Debug tell Local IPv6 is?

I had entered the IPv6 address in the Bind Address field in the previous posts. I just tried entering `wlan0` in the Bind Address field and it reverts to the original behavior (`Local IPv6:  (not set)` and "Protocol not Supported").

**Comment by nivex** [comment] 2019-10-26 15:00
> It is possible for Android app to be notified about default network
> changes:
> 
> [https://developer.android.com/reference/android/net/ConnectivityManager.html#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)](url)
> 
> Based on that info, it might then be possible to change baresip
> bind_address on the fly.

How would this impact usage over a VPN? In that scenario you might want to bind to something that isn't the default network interface.

**Comment by gdt** [comment] 2019-10-26 15:28
Can someone explain why this notion of "binding" to a network interface even exists?

**Comment by juha-h** [comment] 2019-10-26 15:28
> I had entered the IPv6 address in the Bind Address field in the previous posts. I just tried entering `wlan0` in the Bind Address field and it reverts to the original behavior (`Local IPv6: (not set)` and "Protocol not Supported").

OK, so baresip app would need to query from Android IP address of the default interface.

**Comment by juha-h** [comment] 2019-10-26 15:30
> How would this impact usage over a VPN? In that scenario you might want to bind to something that isn't the default network interface.

Then I don't see any other possibility than configuring the interface manually under Bind Address.
That should work already now.

**Comment by juha-h** [comment] 2019-10-26 15:35
> Can someone explain why this notion of "binding" to a network interface even exists?

If there is more that one interface that can be used to reach the Internet, binding would tell which one to use.

**Comment by juha-h** [comment] 2019-10-26 16:06
@nivex I would have a new version for testing that hopefully solves the issue. Could you try it if I make the apk available somewhere?

**Comment by gdt** [comment] 2019-10-26 16:26
> > Can someone explain why this notion of "binding" to a network interface even exists?
> 
> If there is more that one interface that can be used to reach the Internet, binding would tell which one to use.

I can see that this is the intent, but I don't see why this is necessary or beneficial.  If baresip needs to choose a source address, it should be obtained by asking the routing table what source address would be used for a particular destination.   And if it doesn't need to specifically choose, it shouldn't, so that the normal routing process works.

**Comment by juha-h** [comment] 2019-10-26 16:36
Greg Troxel writes:

> I can see that this is the intent, but I don't see why this is
> necessary or beneficial.  If baresip needs to choose a source address,
> it should be obtained by asking the routing table what source address
> would be used for a particular destination.   And if it doesn't need
> to specifically choose, it shouldn't, so that the normal routing
> process works.

This would be OK with me, but see the comments about VPNs.

**Comment by nivex** [comment] 2019-10-26 16:37
> @nivex I would have a new version for testing that hopefully solves the issue. Could you try it if I make the apk available somewhere?

Can do!

**Comment by nivex** [comment] 2019-10-26 16:39
> > > Can someone explain why this notion of "binding" to a network interface even exists?
> > 
> > 
> > If there is more that one interface that can be used to reach the Internet, binding would tell which one to use.
> 
> I can see that this is the intent, but I don't see why this is necessary or beneficial. If baresip needs to choose a source address, it should be obtained by asking the routing table what source address would be used for a particular destination. And if it doesn't need to specifically choose, it shouldn't, so that the normal routing process works.

This works well for things like web clients that just need a stream, but since SIP needs to embed the origin address in the packets it gets a little more complicated. The baresip library would need some way to discover the origin IP for a given destination before sending.

**Comment by gdt** [comment] 2019-10-26 16:42
I am not deeply familiar with the Linux networking stack, but on BSD one can ask the routing socket to do a lookup for a destination and find out the interface that would use use.  Surely there must be similar functionality.   I am not objecting to the notion of finding out what interface will be used by routing; my consternation is about a series of steps which aim to do this and don't follow the same rules.

As for VPN, there is the "all system VPN", and I'd expect route lookups to point to the VPN pseudointerface.  And then there's the per-app VPN feature of orbot.   Still, surely there must be some way to ask the OS "If I send a packet to X, on what interface will it go out".

**Comment by gdt** [comment] 2019-10-26 16:43
A related question is how linphone does this, since it seems to.

**Comment by juha-h** [comment] 2019-10-26 18:36
Kevin Otte writes:

> > @nivex I would have a new version for testing that hopefully solves the issue. Could you try it if I make the apk available somewhere?
> 
> Can do!

Still testing locally.  Will produce the APK tomorrow.

**Comment by juha-h** [comment] 2019-10-27 12:23
@nivex Baresip test apk is now available at [https://box.tutpro.com/tmp/baresip.apk](url).  You should be able to register over IPv6 just by checking `Prefer IPv6` in Settings provided that the available network interface has an IPv6 address.  Checking of `Prefer IPv6` together with `Bind Address` is not currently supported.

In order to install the apk with `adb install baresip.apk`, you may need to first execute `adb uninstall  com.tutpro.baresip`.

**Comment by nivex** [comment] 2019-10-27 14:11
No joy.

* Installed test apk.
* Added account on initial startup.
* Set Prefer IPv6.
* Restarted app

```
D/Baresip Lib(30795): setting dns servers '[fd60:e0:a0f4:321::4]:53,[fd60:e0:a0f4:121::10]:53,172.31.3.30:53'
D/Baresip Lib(30795): setting address '2606:a000:a442:9800:ea91:20ff:fe90:dd04'
D/Baresip Lib(30795): IP-address changed: 172.31.3.28
D/Baresip Lib(30795): ua event (REGISTERING) 
D/Baresip Lib(30795): sending ua/call 3093265712/0 event registering
D/Baresip Lib(30795): --- Network debug ---
D/Baresip Lib(30795):  Preferred AF:  AF_INET
D/Baresip Lib(30795):  Local IPv4:  wlan0|172.31.3.28
D/Baresip Lib(30795):  Local IPv6:  (not set)
D/Baresip Lib(30795):  Domain: 
D/Baresip Lib(30795): net interfaces:
D/Baresip Lib(30795):          lo:  127.0.0.1
D/Baresip Lib(30795):       wlan0:  172.31.3.28
D/Baresip Lib(30795): net routes:
D/Baresip Lib(30795):  Destination                                 Next Hop                                 Iface           Type
D/Baresip Lib(30795):  0.0.0.0/0                                   172.31.3.1                               wlan0           
D/Baresip Lib(30795):  172.31.3.0/24                               ?                                        wlan0           
D/Baresip Lib(30795):  DNS Servers from Config: (3)
D/Baresip Lib(30795):    0: [fd60:e0:a0f4:321::4]:53
D/Baresip Lib(30795):    1: [fd60:e0:a0f4:121::10]:53
D/Baresip Lib(30795):    2: 172.31.3.30:53
D/Baresip Lib(30795): 
D/Baresip Lib(30795): registering UA '3093265712'
D/Baresip Lib(30795): ua event (REGISTERING) 
D/Baresip Lib(30795): sending ua/call 3093265712/0 event registering
D/Baresip Lib(30795): reg: sip:aurora@pbx.home.nivex.net: Register: Destination address required
D/Baresip Lib(30795): ua event (REGISTER_FAIL) Destination address required
D/Baresip Lib(30795): sending ua/call 3093265712/0 event registering failed,Destination address required
```

Added `sip:[2606:a000:a442:9800:5054:ff:fe26:4df6]:5060;transport=udp` to Outbound Proxies as suggested before and got "Protocol not supported".

**Comment by juha-h** [comment] 2019-10-27 14:17
As you can see here, address is set by baresip lib to IPv6 address, but lib changes the address to IPv4 address:
```
D/Baresip Lib(30795): setting address '2606:a000:a442:9800:ea91:20ff:fe90:dd04'
D/Baresip Lib(30795): IP-address changed: 172.31.3.28
```
Weird.  I need to ask help from baresip lib people.

**Comment by juha-h** [comment] 2019-10-28 15:36
@nivex I wrote a new baresip lib API function and with that I'm able to change IPv4 bind address on the fly.  Could you try  [https://box.tutpro.com/tmp/baresip.apk](url) again if it works when you check Prefer IPv6 and leave Bind Address empty?

As before, in order to install the apk with `adb install baresip.apk`, you may need to first execute `adb uninstall com.tutpro.baresip`.

**Comment by nivex** [comment] 2019-10-28 18:44
No joy:

```
D/Baresip Lib(28658): --- Network debug ---
D/Baresip Lib(28658):  Preferred AF:  AF_INET
D/Baresip Lib(28658):  Local IPv4:  wlan0|172.31.3.28
D/Baresip Lib(28658):  Local IPv6:  (not set)
D/Baresip Lib(28658):  Domain: 
D/Baresip Lib(28658): net interfaces:
D/Baresip Lib(28658):          lo:  127.0.0.1
D/Baresip Lib(28658):       wlan0:  172.31.3.28
D/Baresip Lib(28658): net routes:
D/Baresip Lib(28658):  Destination                                 Next Hop                                 Iface           Type
D/Baresip Lib(28658):  0.0.0.0/0                                   172.31.3.1                               wlan0           
D/Baresip Lib(28658):  172.31.3.0/24                               ?                                        wlan0           
D/Baresip Lib(28658):  DNS Servers from System: (3)
D/Baresip Lib(28658):    0: [fd60:e0:a0f4:321::4]:53
D/Baresip Lib(28658):    1: [fd60:e0:a0f4:121::10]:53
D/Baresip Lib(28658):    2: 172.31.3.30:53
D/Baresip Lib(28658): 
D/Baresip Lib(28658): running main loop ...
D/Baresip Lib(28658): allocating UA '<sip:aurora@pbx.home.nivex.net>;stunserver="stun:stun.l.google.com:19302";regq=0.5;pubint=0;regint=0'
D/Baresip Lib(28658): using stunserver: 'stun:stun.l.google.com:19302'
D/Baresip Lib(28658): allocated ua '3095376792'
D/Baresip Lib(28658): updating account of ua 3095376792
D/Baresip Lib(28658): ua event (REGISTERING) 
D/Baresip Lib(28658): sending ua/call 3095376792/0 event registering
D/Baresip Lib(28658): ua event (REGISTER_FAIL) Destination address required
D/Baresip Lib(28658): sending ua/call 3095376792/0 event registering failed,Destination address required
D/Baresip Lib(28658): reg: sip:aurora@pbx.home.nivex.net: Register: Destination address required
```

**Comment by juha-h** [comment] 2019-10-28 19:37
Was Android on your device older than version 6.0 at API level 23?

If so, initialization of active network is not currently supported:
```
               if (Build.VERSION.SDK_INT >= 23) {
                            val activeNetwork = cm.activeNetwork
                            if (activeNetwork != null) {
                                val props = cm.getLinkProperties(activeNetwork)
                                Log.i(LOG_TAG, "Active network properties $props")
                                dnsServers = props.dnsServers
                                netAddresses = cm.getLinkProperties(activeNetwork).linkAddresses
                            } else {
                                Log.w(LOG_TAG, "No active network!")
                            }
                        }
```

**Comment by juha-h** [comment] 2019-10-28 20:50
@nivex Try once more. I got rid of the API  >= 23 dependency.

**Comment by nivex** [comment] 2019-10-29 17:12
Now we've gotten into some weirdness. I uninstalled the previous apk and installed the fresh download. I created the account, which predictably failed until I checked Prefer IPv6. Once it restarted from this setting change, the register failed because I typo'd the password, but it registered cleanly once I fixed it. I then tried to make a call, which failed, notably logging:
```
D/Baresip Lib(14085): call: alloc with params laddr=172.31.3.28, af=AF_INET, use_rtp=1
```
Subsequent restarts of the app have now resulted in Destination address required when attempting to register.

I have attached the full log from this attempt since there's so much going on: [baresip-ipv6-20191029-1705z.txt](https://github.com/juha-h/baresip-studio/files/3784853/baresip-ipv6-20191029-1705z.txt)

**Comment by juha-h** [comment] 2019-10-29 18:53
Kevin Otte writes:

> Now we've gotten into some weirdness. I uninstalled the previous apk
> and installed the fresh download. I created the account, which
> predictably failed until I checked Prefer IPv6. Once it restarted from
> this setting change, the register failed because I typo'd the
> password, but it registered cleanly once I fixed it. I then tried to
> make a call, which failed, notably logging:

I made a new version of baresip.apk available couple of hours ago:

7796 -rw-r--r-- 1 www-data www-data 7981926 Oct 29 18:51 baresip.ap

Was it this one you tried?  If not, give it a try once more.

I need to get feedback from libbaresip devs on this and then do proper
IPv6 testing myself if/when I manage to get IPv6 connectivity to my
device.  I'll let you know when it is done.

**Comment by gdt** [comment] 2019-10-29 18:54
I continue to feel like I am missing something big.   If a host has an AAAA record, and no A record (in the log posted by @nivex I can find the name, look it up, and ping6 it), then why should any configuration be required?  It seems obvious that once the name resolves to AAAA only, then a connection should be attempted via IPv6.  (I can understand settings to indicate which to try first when there are both A and AAAA records.)

**Comment by juha-h** [comment] 2019-10-29 19:51
Greg Troxel writes:

> I continue to feel like I am missing something big.   If a host has an
> AAAA record, and no A record (in the log posted by @nivex I can find
> the name, look it up, and ping6 it), then why should any configuration
> be required?  It seems obvious that once the name resolves to AAAA
> only, then a connection should be attempted via IPv6.  (I can
> understand settings to indicate which to try first when there are both
> A and AAAA records.)

I agree, but the problem is that the device has both IPv4 and IPv6
address and for some reason libbaresip recognizes only the IPv4 one:
```
D/Baresip Lib(23573): --- Network debug ---
D/Baresip Lib(23573):  Preferred AF:  AF_INET6
D/Baresip Lib(23573):  Local IPv4:  wlan0|172.31.3.28
D/Baresip Lib(23573):  Local IPv6:  (not set)
```

**Comment by gdt** [comment] 2019-10-29 19:53
So this seems like a libbaresip bug, which is https://github.com/alfredh/baresip/issues/831 and I guess you are trying to work around it.  I really wonder how much this is related to the need-for-source-selection issue.

**Comment by nivex** [comment] 2019-10-29 20:56
> I made a new version of baresip.apk available couple of hours ago: 7796 -rw-r--r-- 1 www-data www-data 7981926 Oct 29 18:51 baresip.ap Was it this one you tried? If not, give it a try once more. I need to get feedback from libbaresip devs on this and then do proper IPv6 testing myself if/when I manage to get IPv6 connectivity to my device. I'll let you know when it is done.

Yes, that appears to be the one I used:
kjotte@daedalus:/tmp$ ls -l baresip.apk 
-rw-rw-r-- 1 kjotte kjotte 7981926 Oct 29 12:51 baresip.apk
kjotte@daedalus:/tmp$ sha1sum baresip.apk 
40ebcae75410891f60b5f8440f493af88618a9b2  baresip.apk

**Comment by nivex** [comment] 2019-10-29 21:04
> I continue to feel like I am missing something big. If a host has an AAAA record, and no A record (in the log posted by @nivex I can find the name, look it up, and ping6 it), then why should any configuration be required? It seems obvious that once the name resolves to AAAA only, then a connection should be attempted via IPv6. (I can understand settings to indicate which to try first when there are both A and AAAA records.)

The problem is that the app is not correctly detecting **its own** address. As I mentioned in a previous reply, SIP is special in that a client needs to put its IP address in the messages it sends for things like RTP session set up.

baresip-core on Ubuntu is working fine on the same network, so there's something Android specific getting in the way.

**Comment by juha-h** [comment] 2019-10-30 06:58
Greg Troxel writes:

> So this seems like a libbaresip bug, which is
> https://github.com/alfredh/baresip/issues/831 and I guess you are
> trying to work around it.  I really wonder how much this is related to
> the need-for-source-selection issue.

I too suspect that there is some bug in IPv6 handling in the lib.  If I
start baresip with arg "-6 Prefer IPv6" or with config param
"net_prefer_ipv6 yes" in non-IPv6 Debian Linux environment, it fails to
register:
```
ua: SIP register failed: Protocol not supported
account: failed to register ua 'sip:test@test.tutpro.com' (Protocol not supported)
```

**Comment by juha-h** [comment] 2019-11-02 19:18
I got info from libbaresip folks.  It turned out that Andoid includes `getifaddrs` function at API level 24.  baresip app currently targets API level 21 and thus this function is not available in libbaresip.  

The options thus are:  (1) drop IPv6 support from baresip or (2) increase API target to level 24.  I'm afraid that the latter option would eliminate baresip from too many users.

**Comment by licaon-kter** [comment] 2019-11-02 19:25
@juha-h targetsdk =/= minsdk, right?

If it does not work for them on 21 you can if-then-else it and popup an info box on start "no ipv6 on your android"

**Comment by gdt** [comment] 2019-11-03 00:52
(Without digging into target/min) As a worst case, there is also the option of providing two builds, a mainstream one that does IPv6 and expects relatively recent Android, and one that accommodates Android 5 and 6.

**Comment by juha-h** [comment] 2019-11-03 13:19
@nivex It turned out that Android does not have getifaddrs function that supports getting of IPv6 addresses before API level 24.  Currently API level of libbaresip is 21, which explains why your IPv6 was not detected.

We introduced two new baresip API functions that can be used to set IPv6 address and IP protocol preference from Android.  I created a new apk `https://box.tutpro.com/tmp/baresip.apk` that uses them.  If you have time, give it a try and show what 'adb logcat | grep Baresip' tells.

 I would very much like to test it myself, but my mobile operator does not support IPv6 and my Android device is not able to get IPv6 address using DHCP from my WiFi router.

**Comment by nivex** [comment] 2019-11-03 18:31
Installed apk from that URL. When I attempt to go back from the account screen to the main screen, I get an error:

Notice
Baresip failed to start. This may be due to an invalid Listen Address or TLS file. They have been reset. Restart baresip.
Ok

Tapping Ok exits the app. This error is displayed every time I reach the main screen, rendering the app unusable. Here is the full log from the first attempt: [baresip-ipv6-20191103-1825z.txt](https://github.com/juha-h/baresip-studio/files/3801954/baresip-ipv6-20191103-1825z.txt)

I realize my Android version is ancient, so I understand if this is unresolvable for this version. I am hopeful to get some new hardware in the coming months that will support a newer Android version.

**Comment by nivex** [comment] 2019-11-03 18:35
I'm not completely sure what I did, but after writing the previous post I went back in to the app to poke around. It registered cleanly and is able to place a call over IPv6!

Here's a log from startup through successful call just so you have something working to compare with: [baresip-ipv6-20191103-1834z.txt](https://github.com/juha-h/baresip-studio/files/3801960/baresip-ipv6-20191103-1834z.txt)

**Comment by juha-h** [comment] 2019-11-05 18:48
@nivex I found a mobile operator that supports IPv6 and bought their prepaid SIM.  With that I was able to test baresip IPv6 code, found bugs, and fixed them.  Now in my tests setup where Prefer IPv6 is checked works OK with this:
```
https://box.tutpro.com/tmp/baresip.apk
```
Most of the time baresip can also dynamically switch between WLAN (which does not have IPv6) and mobile.  Sometimes, however, baresip does not get network availability event from Android when WLAN connection is lost and mobile connection should become available again.

**Comment by juha-h** [comment] 2019-11-08 15:18
I think that now also switching between mobile and wlan networks works even when Android has bugs in announcing loss and availability of networks.

If Prefer IPv6 is checked, IPv6 will be used if currently active network has an IPv6 address.

I'll close this issue now.  Please reopen if IPv6 related issues still exist and provide `adb logcat | grep Baresip` output showing them.

**Closed by juha-h** 2019-11-08 15:18 UTC

**Comment by nivex** [comment] 2019-11-09 20:56
Started a new job this week so I only just now had a chance to test the latest package out. It appears to be working correctly. Thank you!
