### ISSUE TITLE
8.0 no audio, no ZRTP prompt

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#35] opened 2019-05-24 14:41 UTC
F-Droid
AOSP9 <> Samsung 6.0.1

Steps:
* call
* pickup
* appears connected on both sides
* no sound
* no zrtp prompt

Logcat: https://gist.github.com/licaon-kter/1ec6ad7660b972c02df5f1c571748d2b

**Comment by juha-h** [comment] 2019-05-24 17:17
Licaon_Kter writes:

> AOSP9 <> Samsung 6.0.1
> 
> Steps:
> * call
> * pickup
> * appears connected on both sides
> * no sound
> * no zrtp prompt
> 
> Logcat: https://gist.github.com/licaon-kter/1ec6ad7660b972c02df5f1c571748d2b

There is no zrtp prompt because there is no response to zrtp hello from
the other side.

What comes to no audio, echo cancellation is not currently supported
when codec is used, but that should not cause audio to fail.  Just
tested with all three devices mentioned in other threads, and audio
worked both ways.

**Comment by licaon-kter** [comment] 2019-05-24 17:20
So...how do I debug?

**Comment by juha-h** [comment] 2019-05-24 17:32
Licaon_Kter writes:

> So...how do I debug?

If you mean audio, try using PCMA or PCMU codec to see if echo
cancellation is the issue.

Regarding ZRTP, make sure the other party supports ZRTP and responds to
zrtp hello (you see that in adb logcat).

**Comment by licaon-kter** [comment] 2019-05-24 17:54
The other party runs baresip as well. ;)

Will se about codecs.

**Comment by licaon-kter** [comment] 2019-05-24 19:02
@juha-h identical setup, devices are beside one another

**Comment by juha-h** [comment] 2019-05-24 19:22
Licaon_Kter writes:

> @juha-h identical setup, devices are beside one another

I just tried call between two baresips and got after call had
established:
```
05-24 22:09:39.820  7065  7188 D Baresip Lib: bar@test.tutpro.com: Call established: sip:foo@test.tutpro.com
05-24 22:09:39.823  7065  7188 D Baresip Lib:  [  zrtp utils]: 	Send <HELLO> ssrc=2615488084 seq=41308 size=148. Stream 0:CLEAR:START
05-24 22:09:39.825  7065  7187 D Baresip Lib: sending ua/call 2516525384/2516445064 event call established
05-24 22:09:39.826  7065  7187 D Baresip Service: uaEvent got event call established/2516525384/2516445064
05-24 22:09:39.829  7065  7187 D Baresip Service: AoR sip:bar@test.tutpro.com call 2516445064 established
05-24 22:09:39.833  7065  7187 D Baresip : Saving history of size 27
05-24 22:09:39.858  7065  7187 D Baresip Service: Call volume of stream 3 is 9
05-24 22:09:39.860  7065  7065 D Baresip : Handling service event 'call established' for 2516525384
05-24 22:09:39.861  7065  7188 D Baresip Lib:  [  zrtp utils]: Received <Hello   > packet with ssrc=2639358621 seq=39082/39082 size=148. Stream0:CLEAR:START.
05-24 22:09:39.861  7065  7188 D Baresip Lib:  [ zrtp engine]: 	Processing HELLO from baresip/zrtp V=1.10, P=0, M=0.
```
That is, baresip receiced zrtp hello from the other side.  In your log,
baresip never received the hello.

Could you take logcat from the other baresip (called party)?

**Comment by licaon-kter** [comment] 2019-05-26 11:00
8.0.2 now it suddenly works, I don't understand but... :-|

**Comment by licaon-kter** [comment] 2019-05-29 09:05
Another day, another test, 8.3.0 self build on both (AOSP9 <> Samsung 6.0.1), but today it's not working...

**Comment by juha-h** [comment] 2019-05-29 10:44
Licaon_Kter writes:

> Another day, another test, 8.3.0 self build on both (AOSP9 <> Samsung
> 6.0.1), but today it's not working...

Check from logcat if zrtp is active on both devices when you start
baresip:

```
05-29 13:38:08.649 29684 29684 W Baresip : module zrtp.so
...
05-29 13:38:08.649 29684 29684 W Baresip : zrtp_hash yes
...
05-29 13:38:08.830 29684 29708 D Baresip Lib:  [   zrtp main]: INITIALIZING LIBZRTP...
...
05-29 13:38:08.831 29684 29708 D Baresip Lib:  [   zrtp main]: INITIALIZING LIBZRTP - DONE
05-29 13:38:08.831 29684 29708 D Baresip Lib: mediaenc: zrtp
05-29 13:38:08.831 29684 29708 D Baresip Lib: zrtp:  cache_file:  /data/user/0/com.tutpro.baresip/files/zr
05-29 13:38:08.831 29684 29708 D Baresip Lib: tp_cache.dat
05-29 13:38:08.831 29684 29708 D Baresip Lib:        zid_file:    /data/user/0/com.tutpro.baresip/files/zrtp_zid
05-29 13:38:08.831 29684 29708 D Baresip Lib:        zid:         xxx
```

Then when you make call, check from logcat, that zrtp session is started
and after answer that there is HELLO messages sent and received both
ways.

**Comment by licaon-kter** [comment] 2019-05-29 17:18
Ok, so looking at the log: https://gist.github.com/licaon-kter/84d8b75b507a4e2d518fac66bb0c0c1d

Why does Baresip try to connect to a RFC1918 address?

Same setup and issue with Linphone: https://github.com/BelledonneCommunications/linphone-android/issues/657

**Comment by juha-h** [comment] 2019-05-29 18:29
Licaon_Kter writes:

> Ok, so looking at the log: https://gist.github.com/licaon-kter/84d8b75b507a4e2d518fac66bb0c0c1d
> 
> Why does Baresip try to connect to a RFC1918 address?

I'm not sure if I understood the question, but baresip sends initial
request based on outbound proxy uri if one defined or based on r-uri.
In both cases, if uri host is domain name, naptr/srv/a lookup is done on
it.

**Comment by juha-h** [comment] 2019-10-13 07:57
Is this still an issue?  If so, could you clarify what exactly the issue is?

**Comment by juha-h** [comment] 2019-10-14 09:40
Check if this helps: https://github.com/juha-h/baresip-studio/issues/54#issuecomment-541580338

**Comment by juha-h** [comment] 2019-11-18 05:43
This appears to be caused by libbaresip not currently supporting multihoming as reported in  #54.  Is it OK that I close this one, since the issue is better covered there?

**Comment by licaon-kter** [comment] 2019-11-18 06:18
As you see fit, I have yet to retest.

**Closed** 2019-11-18 06:18 UTC
