### ISSUE TITLE
List of dns addresses is not cleared on new config

### ISSUE THREAD

**Issue by KORuL** [juha-h/baresip-studio#392] opened 2023-07-07 07:19 UTC
Good afternoon I got one problem in the latest versions.
I'm creating a call from the entry panel and initializing baresip to call. Before starting Baresip, I form a config with two
dyn_dns yes
                                                                                                     dns_server 213.87.142.84:53
                                                                                                     dns_server 213.87.142.85:53

[2023-07-07 10:09:25.795 14411-14824 _BaresipServic.txt](https://github.com/juha-h/baresip-studio/files/11977328/2023-07-07.10.09.25.795.14411-14824._BaresipServic.txt)

The baresip service starts and works correctly, after that I completely end the baresip service, stop baresip.

Next, I switch the network from mobile Internet to wifi and make a new call, re-form the config, start the baresip service again and give it a new config with one dns address, it eats it up correctly, and in the logs it displays that it now has not 2, not 1 dns address, and 3. How so? How to make him forget about past dns addresses?

(if the first call will be 4 dns addresses, and the next 1, then it will not add a new one to the list, and the call will not go through)

I am attaching the logs of 2 calls

[2023-07-07 10:09:25.795 14411-14824 _BaresipServic.txt](https://github.com/juha-h/baresip-studio/files/11977343/2023-07-07.10.09.25.795.14411-14824._BaresipServic.txt)

**Comment by juha-h** [comment] 2023-07-07 10:18
KORuL writes:

> I'm creating a call from the entry panel and initializing baresip to
> call. Before starting Baresip, I form a config with two 
> dyn_dns yes
>                                                                                                      dns_server 213.87.142.84:53
>                                                                                                      dns_server 213.87.142.85:53

What do you mean by "before starting baresip"?  DNS servers are
configured via Settings when the app is running.

I just tested by adding and removing DNS servers and logcat didn't show
any extra DNS servers when it printed the config.

**Comment by KORuL** [comment] 2023-07-07 10:41
starting  - baresipStart
stoping - baresipStop

**Comment by KORuL** [comment] 2023-07-07 10:41
configured when baresipStoped state before call baresipStart

**Comment by juha-h** [comment] 2023-07-07 11:17
Sorry but I don't have resources to handle anything else than the baresip app installed from F-Droid or from the releases.

**Comment by juha-h** [comment] 2023-07-15 14:29
I'll close this since I got the impression that the issue is not related to baresip app installed from F-Droid or from GitHub releases.

**Closed by juha-h** 2023-07-15 14:29 UTC
