### ISSUE TITLE
Notification on android could use some work....

### ISSUE THREAD

**Issue by Rstment25** [juha-h/baresip-studio#309] opened 2023-02-16 04:24 UTC
Take a look at the video below ( I think you can watch without downloading it )
https://drive.google.com/file/d/1qhyg8TcD_pwQZRFojiuZdVScXzSZ-jB6/view?usp=sharing

In the video I'm playing with opening/closing baresip notification , notice how indicator only shows up when notification is closed?

When you open/expand notification it shows you nothing? But when the notification is closed/collapsed it shows status bar indicator? Isn't that odd behaviour...

Is it possible to have it show status bar indicator ALL the time? It already shows it with notification collapsed, it shouldn't be hard to have it show indicator when it's open as well?

Android by default shows baresip notification as open ( No indicator is shown , you have to minimise notification in order to see the indicator - very counterproductive because if for some reason indicator is showing disconnected you now have to open notification again in order to be able to click on it and open the app )

**Comment by juha-h** [comment] 2023-02-16 05:29
I don't know what you mean. There is always symbol b on the status bar, when baresip is running. When I swipe down the the screen, I don't see any up/down indicators in baresip notification https://box.tutpro.com/tmp/shot.jpg.

**Comment by Rstment25** [comment] 2023-02-16 05:51
![IMG_20230216_064745](https://user-images.githubusercontent.com/32986283/219279762-2998a09d-1092-4a83-9012-2487fb01d0b1.jpg)
This is what I mean btw, only shows up when notification is collapsed

**Comment by juha-h** [comment] 2023-02-16 06:17
Rstment25 writes:

> ![IMG_20230216_064745](https://user-images.githubusercontent.com/32986283/219279762-2998a09d-1092-4a83-9012-2487fb01d0b1.jpg)
> This is what I mean btw, only shows up when notification is collapsed

It shows the baresip and the dots one per account then you pull down
the notification bar.  On notification bar, there is only the b image.

This is how it has been forever and I don't see anything wrong with it.

**Comment by juha-h** [comment] 2023-02-17 07:38
I'll close the issue, since there is nothing that needs to be done.  The behavior is as intended.

**Closed by juha-h** 2023-02-17 07:38 UTC

**Comment by Rstment25** [comment] 2023-03-31 13:38
> I'll close the issue, since there is nothing that needs to be done. The behavior is as intended.
![Screenshot_20230331-153631_Trebuchet](https://user-images.githubusercontent.com/32986283/229135263-7ed0d702-a2f4-470a-8147-017606ea0a89.png)
Feels bad... There were 2 or 3 updates since I opened this issue and now it no longer shows indicator at all

**Comment by juha-h** [comment] 2023-03-31 18:56
See this https://github.com/juha-h/baresip-studio/issues/345.

**Comment by Rstment25** [comment] 2023-04-03 14:19
![Screenshot_20230403-160725_Brave](https://user-images.githubusercontent.com/32986283/229534315-b95c660d-178a-4b18-8752-dd869fa78afc.png)


> See this #345.

This behavior is very similar to what I reported above - in their default state notifications don't show , only in certain special states they show up ( I understand there should be different states of notifications - lockscreen being one of them, As you start dragging up to close notifications menu that could be another state ? )

**Comment by juha-h** [comment] 2023-04-03 14:32
Rstment25 writes:

> This behavior is very similar to what I reported above - in their
> default state notifications don't show , only in certain special
> states they show up ( I understand there should be different states of
> notifications - lockscreen being one of them, As you start dragging up
> to close notifications menu that could be another state ? )

I don't think that application can do anything about Android 13 default
notification settings.  See the examples in
https://github.com/juha-h/baresip-studio/issues/345#issuecomment-1491341952.
Or what is your suggestion?

**Comment by Rstment25** [comment] 2023-04-03 14:42
I am using pure android as it gets - Aosp without gapps

> Rstment25 writes:
> This behavior is very similar to what I reported above - in their default state notifications don't show , only in certain special states they show up ( I understand there should be different states of notifications - lockscreen being one of them, As you start dragging up to close notifications menu that could be another state ? )
> I don't think that application can do anything about Android 13 default notification settings. See the examples in [#345 (comment)](https://github.com/juha-h/baresip-studio/issues/345#issuecomment-1491341952). Or what is your suggestion?

My suggestion would be for you to try on AOSP rom without GAPPS ( google services )

Lineage OS is what me and the other guy reporting same issue are using...

He is on Android 13 and I am on Android 12 - same behavior

I suspect notifications are broken... but the only reason they work for you u have Google Services Framework it handles all notifications , hence

**Comment by Rstment25** [comment] 2023-04-03 14:48
"My suggestion would be for you to try on AOSP rom without GAPPS ( google services )"

This could be possible via DSU (Open developer options, click on DSU and select package without GMS )

![IMG_20230403_164818](https://user-images.githubusercontent.com/32986283/229545663-afd9cfdd-fd80-45aa-bcb6-31ba3a00732e.jpg)

**Comment by juha-h** [comment] 2023-04-03 15:54
My A04 does not have DSU setting in Developer Options.  Pixel 7 emulator has "DSU Loader" setting.  I chose the one w/o GSM, agree the terms, and started baresip.  Pull down notification worked same way as before:

In Pixel 7 emulator (Android 13) with minimize on: 'baresip icon + time'. Reg dots are shown under it after touching v. After touching ^, 'baresip icon + time'.

In Pixel 7 emulator with minimize off: 'baresip icon + time'. Reg dots are shown under it without touching anything. After touching ^, 'baresip icon + reg dots'.
