### ISSUE TITLE
IM  -SIP message

### ISSUE THREAD

**Issue by rabongithub** [juha-h/baresip-studio#191] opened 2021-10-28 16:50 UTC
baresip always display received similar two message. and when sent out message from baresip, after 4/5 message it does not send anymore, need to restart.

**Comment by rabongithub** [comment] 2021-10-29 23:57
i did not do adb logcat | grep Baresip, but yes sip trace and also checked from asterisk . i have to get some other device to test.

**Comment by juha-h** [comment] 2021-11-13 14:52
Closing since I can't reproduce this issue.

**Closed by juha-h** 2021-11-13 14:52 UTC
