### ISSUE TITLE
SMS composition field is not cleared when VTT is used in place of keyboard input, leading to double-sends of same text

### ISSUE THREAD

**Issue by xandark** [juha-h/baresip-studio#502] opened 2024-10-22 02:51 UTC
With the latest version of baresip 61.0.1 installed from F-Droid, I notice a subtle GUI issue that I can replicate. This is using Google's Gboard for the keyboard/dictation on a Pixel 7 with the latest OS.

When I am composing a text message, if I use the on-screen keyboard to tap out a message and then tap the "send" icon, the message composition field that was holding my message is cleared and the on-screen keyboard is hidden. All good.

However, if I *don't* use the on-screen keyboard, but rather tap on the keyboard's mic to begin voice-to-text dictation, the line edit field fills in with the contents of my voice dictation, as expected, yet it doesn't get cleared later. When I tap the "send" icon, the message composition field is not cleared even though the keyboard is hidden and the text message is sent. 

So it appears that the text *wasn't* sent because it's still visible at the bottom of the screen in the editable composition field. 

For awhile, I kept sending two text messages because I would see my message still visible on the bottom of the screen and then tap the "send" icon again, thinking that it didn't send because it's still there.

It seems as if baresip's logic is that it will only clear the message composition field if it detected that the on-screen keyboard was used to type on. Could it be changed to always clear the composition field when the "send" icon is tapped?

**Comment by juha-h** [comment] 2024-10-23 11:26
I tried with Pixel 7 API 34 Emulator.

After clicking New message field, keyboard popped up. Then I clicked the soft keyboard mic icon and got "Speak now" prompt. After speaking, the text appeared in New message field.  Then I clicked the send button and the sent text appeared at the bottom of the message list, New message field was cleared, and soft keyboard disappeared.  So everything worked OK.

Since I cannot fix something that I cannot reproduce, I'll close this issue.

**Closed by juha-h** 2024-10-23 11:26 UTC

**Comment by juha-h** [comment] 2024-10-24 07:06
My Samsung device does not have Gboard app, but Android Studio  Pixel 7 API 34 Emulator has.  I retried with both and I do not need to type anything after translation or mic input.  And as can be seen in the above code, it clears the message text field IF sending of the message succeeds.   You could check with `adb logcat` if some error messages appear during the process.

**Comment by juha-h** [comment] 2024-10-24 08:34
Is it not enough that you touch the message field after the dictate or do you really need to add a character to it?

**Comment by juha-h** [comment] 2024-10-25 06:56
@xandark So it was not lack of focus.  I now added a debug message and setText("") to the code:
```
                     if (Api.message_send(ua.uap, msgUri, msgText, time.toString()) != 0) {
                        Toast.makeText(applicationContext, "${getString(R.string.message_failed)}!",
                                Toast.LENGTH_SHORT).show()
                        msg.direction = MESSAGE_UP_FAIL
                        msg.responseReason = getString(R.string.message_failed)
                    } else {
                        Log.d(TAG, "Clearing newMessage")
                        newMessage.setText("")
                        newMessage.text.clear()
                        BaresipService.chatTexts.remove("$aor::$peerUri")
                    }
```
They are in this apk: https://box.tutpro.com/tmp/baresip.apk.  Could you give it a try?  Save before install and then restore.  `adb logcat | grep Baresip` should show the debug message when you touch the send icon and sending of the message succeeds.

**Comment by xandark** [comment] 2024-10-25 20:20
Okay, great! I'll try to do that tonight.

**Comment by xandark** [comment] 2024-10-25 20:22
BTW, I've never done this before. Excuse me for the basic question but what am I backing up? Is there a database that adb can back up?

**Comment by juha-h** [comment] 2024-10-26 06:10
xandark writes:

> BTW, I've never done this before. Excuse me for the basic question but
> what am I backing up? Is there a database that adb can back up?

You backup from Settings your baresip configuration, because it will get
lost when you install the baresip.apk, which is not from F-Droid.

**Comment by xandark** [comment] 2024-11-08 01:37
I noticed with the latest update from F-Droid your code change fixed the issue, thank you.
