### ISSUE TITLE
Integration with contacts

### ISSUE THREAD

**Issue by drzraf** [juha-h/baresip-studio#135] opened 2021-01-15 16:22 UTC
In most "alt-phone" applications (from SIP to Signal), one can browse the usual (native or not) "contacts" list using the "contacts" app then press "Call" and choose which app to use ("Native", "CSipSimple", ...)
That means no need for sync'ing contacts and usability benefits.

It's understandable that **contacts created within baresip not be exported** to a (possibly google-owned) "contacts" application.
But the other way would be safe and respect user's privacy choices.
(Users may even be using a FLOSS app for managing their "Contact", privacy being even less of a problem).

This feature would be a major usability improvment.

(https://github.com/baresip/baresip/issues/1190)

**Comment by juha-h** [comment] 2021-01-15 16:43
In order to make baresip call from a Contacts app, there needs to be some means to register baresip as a possible target application for outbound calls from "Android Contacts".  Can you point to some document that describes the registration method?

Also, if there are more than one account defined in baresip app, how would the "Android Contacts" call account be chosen?  Perhaps baresip user should be able to configure one of the accounts as "Android Contacts" account?

**Comment by gdt** [comment] 2021-01-15 18:14
I think the "which account" question is a good one, and it points out a larger call routing question.   I don't see it as specifically related to calling from contacts vs just entering a SIP URI.   I'd say that if the domain matches one of the contacts, use that, and if not there should be some "default account" used for outgoing calls with a domain that doesn't match any of them.     Perhaps there could be a domain->account lookup map, but that seems more complicated than I hope would be needed.

**Comment by juha-h** [comment] 2021-01-15 18:34
I'll investigate.  Looks like it is possible to register to receive action dial intent from other applications. But for sure that is security breach, since all apps (and possible also Google) that have registered to received the intent get to know about the call.

**Comment by gdt** [comment] 2021-01-16 00:48
I don't understand why you think baresip receiving the intent makes the situation worse, other than perhaps users might have to workaround the lack of it by opening baresip for the 1% of calls made that way.   Really  the OS (and the user's choice of which ROM to run and which other apps to install) control the security situation, and I don't think individual apps should militate against that, especially for users that run de-Googled ROMs.

**Comment by juha-h** [comment] 2021-01-16 11:11
Turns out that it is possible to define that baresip is a registered phone app and that is can receive dial requests from other apps.  

After that definition, I can select in Settings/Apps/baresip that baresip is the default phone app.  Once I made that selection, Contacts app on my Android 10 device started to send events to baresip when I tried to make a call from Contacts.

But I have not found a way to select which registered phone app Contacts app should use for a call.  It always uses the phone app than has been chosen to be the default phone app.

**Comment by juha-h** [comment] 2021-01-16 12:17
Choosing baresip to be the default phone app does not sound practical, since usually only a minority of calls are baresip calls.

How about if baresip at start would automatically fetch Android contacts and merge them with its own Contacts and keep them there until user quits baresip?

**Comment by drzraf** [comment] 2021-01-16 13:29
Linphone, for example, shows itself along other "phone apps" after
installation.

**Comment by juha-h** [comment] 2021-01-16 14:22
Raphaël Droz writes:

> Linphone, for example, shows itself along other "phone apps" after
> installation.

As I wrote, I made a test and was able to do the same with baresip.

The problem is, how to make Contacts application to choose, which phone
app to use rather than always use baresip if is has been selected as
the default phone app.

**Comment by gdt** [comment] 2021-01-16 15:31
In contacts (AOSP via lineage) for users that have signal I am seeing in addition to the phone icon also I have a signal message and signal call icon.   So the Signal sources are probably helpful to figure out how to do that.

A big question is how to configure baresip to have it offer to handle sip/sips URis only or also PSTN numbers.  It seems to me that a SIP app needs a way to convey in registration if it is a valid destination for E.164 addresses, vs only for sip/sips URIs.

**Comment by gdt** [comment] 2021-01-16 15:34
As for contacts, my preference is to simply use the contacts database on the phone.    I realize there are concerns about privacy, but I think that's misplaced as the contacts database is the proper place for contacts.   People who care about privacy will either use the local contacts database, or they will use something like DAVx5 to sync to self-hosted CARDDAV.   Certainly that allows one to open baresip and find a contact and call them, but I don't think that makes being able to receive intents for calls something that shouldn't happen.

**Comment by juha-h** [comment] 2021-01-17 16:16
I made progress on this.  Now if Android contact app contact is sip: or tel: URI, it is possible to complete call action with baresip.

When the CALL intent arrives to baresip from contact app, baresip tries to match the host part of the sip: URI to an account and if one is found, uses that.  If no such account if found or if the URI is tel: URI, baresip chooses an account that has been checked as Default Account or first account if none is checked as Default Account.

My Android contact app (Android One default app) does not allow me to define a tel: URI to a contact, but just phone numbers and one sip: URI. It is not possible to choose baresip when calling contact's phone number.  Same thing with Linphone.

@gdt If you are building baresip yourself, please give latest master a try.

**Comment by juha-h** [comment] 2021-01-19 18:11
baresip 26.1.0 and baresip+ 11.0.0 are now available at least from Play store.  They allow calls to be made from those Android contacts that have sip URI defined.

I'm also working on contact feature that allows baresip to upload to its contact to Android contacts.  I'll close this now.  Open a new one when you notice that something is missing.

**Closed by juha-h** 2021-01-19 18:11 UTC

**Comment by drzraf** [comment] 2021-01-20 16:23
Thank you for the effort, but I still can't call a phone number using baresip from `contacts`.

I guess it lay in the stance `if Android contact app contact is sip: or tel: `?

Then if a contact phone number is _just_ `+123456789...` I'm not offered baresip as an option (only native `Phone`, `Linphone` and `Skype` are). Is this expected?
(tested on Android 9)

**Comment by juha-h** [comment] 2021-01-20 18:32
Raphaël Droz writes:

> Then if a contact phone number is _just_ `+123456789...` I'm not
> offered baresip as an option (only native `Phone`, `Linphone` and
> `Skype` are). Is this expected?

My Android 9 device does not offer any SIP apps (Linphone etc.) to make
calls to normal phone numbers.  I don't know what is going on.

**Comment by drzraf** [comment] 2021-01-20 18:44
That was on Android 7 (sorry).
![Screenshot_20210120-154031](https://user-images.githubusercontent.com/1169926/105220333-52c5fa00-5b36-11eb-9d3b-bbfd7775bcd3.jpg)

But I could try Linphone on Android 9 to confirm this.
