### ISSUE TITLE
Info button does nothing on Android 6

### ISSUE THREAD

**Issue by licaon-kter** [juha-h/baresip-studio#16] opened 2019-02-13 11:24 UTC
But on Android 9 call info (codec and such) is shown

5.3.1 F-Droid

**Comment by juha-h** [comment] 2019-02-15 20:43
I don't have Android 6 to test. Does adb logcat show some error messages when you press info button?

**Comment by juha-h** [comment] 2019-02-22 02:45
Closing due to lack of response.  Reopen if you get more info.

**Comment by licaon-kter** [comment] 2019-02-22 08:01
Didn't get a chance to adb into it, will do as the update hits F-Droid.

**Comment by licaon-kter** [comment] 2019-05-24 12:36
Could you reopen this? I've lost track of it because it was closed.

Still an issue on 8.0, will try to get it to a PC soon.

**Comment by juha-h** [comment] 2019-05-24 16:53
I have an Android 5.1, 7,1,1 and 9.0 device all from different vendors.  I just tested and info button worked on all of them using latest baresip version.  A friend has 8.1 device and info button works also in that. Info button is quite small and easy to miss.  Did you try tapping it more than once?

I'll reopen this if you can provide logcat, but it may also be some bug in the software of your device.  Android Studio IDE does not report anything Android version specific in the code handling info button.

**Comment by licaon-kter** [comment] 2019-05-24 17:27
Maybe the 8.0 was misunderstood, as the title says Android 6.0.1...8.0 is baresip version. :)

**Comment by juha-h** [comment] 2019-05-24 17:37
Licaon_Kter writes:

> Maybe the 8.0 was misunderstood, as the title says Android 6.0.1...8.0
> is baresip version. :)

As I mentioned, I cannot reproduce this on any the found different
Android versions I have.  There is no change to info button handling in
recent baresip versions.

**Comment by licaon-kter** [comment] 2019-05-26 10:54
8.0.2, ADB, nothing logged when pressing the button.

**Comment by juha-h** [comment] 2019-05-26 11:09
Licaon_Kter writes:

> 8.0.2, ADB, nothing logged when pressing the button.

Baresip app does not produce any log messages when info button is
pressed.  If Android didn't log any errors, then it is hard to tell what
the problem is.

As I mentioned, info button works on four different devices (each with
different API version) that I have had access.

Have you tried on more than one device?

**Comment by licaon-kter** [comment] 2019-05-26 11:29
Yes, works on AOSP9.

**Comment by juha-h** [comment] 2019-05-26 11:38
Sorry, I have Android 5.1,  7.1.1, 8.1, and 9.0 device to try and on all those Info burrot works.
One thing that came to mind is screen size.  I don't know what would happen if the line where Info button is located does not have enough pixels for all the icons and their margins.

**Comment by licaon-kter** [comment] 2019-05-26 11:59
The icons are there. Not sure what margins could be at fault.

One thing for me to test is going back to native density (via ADB `wm density reset`), now it's lower to get a smaller UI.

That being said, on AOSP9 my density is smaller too yet it works fine.

**Comment by juha-h** [comment] 2019-05-26 12:16
Then I don't density is the issue.  I just just pushed a commit that prints log message when onClick is event received and shows alert even when no info is available.

**Comment by licaon-kter** [comment] 2019-05-29 08:55
Ok, 8.3.0 self build, press button:
```
Call Info
No info available.
```
Should I try to extract some debug logs too?

**Comment by juha-h** [comment] 2019-05-29 10:07
Licaon_Kter writes:

> Ok, 8.3.0 self build, press button:
> ```
> Call Info
> No info available.
> ```
> Should I try to extract some debug logs too?

In 8.3.0 there is this log message:
```
infoButton.setOnClickListener {
         Log.d("Baresip", "Info Button was clicked")
```
So if you see it in logcat, info alert should show up.

I just pushed a commit to master that makes sure that info button is
also enabled, when it becomes visible.  Perhaps your device requires
that.

**Comment by juha-h** [comment] 2019-05-29 16:22
Is this still issue after you build baresip from master?

**Comment by licaon-kter** [comment] 2019-05-29 17:07
Still
```
Call Info
No info available.
```

Log https://gist.github.com/licaon-kter/84d8b75b507a4e2d518fac66bb0c0c1d says:
```
Baresip : Info Button was clicked
Baresip Lib: failed to get call status
Baresip Lib: failed to get call audio codecs
```

**Comment by juha-h** [comment] 2019-05-29 18:18
So there is no issue with the UI, i.e., info button does its job.

Problem is that baresip lib does not get call nor codec info from baresip process.   Based on the log, the reason seems to be that you clicked info button after a call was closed by baresip process. 

Based on the log, the situation is very confusing.  Looks like have three calls (3105107592, 
3104886296 and 3106277968) and only 3105107592 is known to UI:
```
Baresip : Adding outgoing call 3104756272/3105107592/sip:user2@sip.mydomain.tld
Baresip Lib: sending ua/call 3104756272/3104886296 event call closed,Connection reset by peer
Baresip Service: AoR sip:user1@sip.mydomain.tld call 3104886296 that is closed is not found
Baresip Service: AoR sip:user1@sip.mydomain.tld call 3105107592 established
Baresip Service: uaEvent got event call closed,Connection reset by peer/3104756272/3106277968
Baresip Service: AoR sip:user1@sip.mydomain.tld call 3106277968 that is closed is not found
Baresip : Info Button was clicked
Baresip Lib: failed to get call status
Baresip Lib: failed to get call audio codecs
Baresip Service: uaEvent got event call closed,Connection reset by user/3104756272/3105107592
```
I suspect that info button tries to get call info of a call that does not anymore exist.

Can you explain, how you made the test and why the log shows more than one call?

I just pushed a commit to master that adds log message telling which call failed to produce call and
codec info.

**Comment by licaon-kter** [comment] 2019-05-29 19:17
I've called several times, from both devices, nothing happened, not even the initial connection, restarted the app on both.

Then it worked, picked up, pressed the button.

Do note that on AOSP9 even if nothing works, nooice/zrtp, the info shows time connected and opus and stuff.

The log had all these and I've tried (and failed I guess) to keep only the last call.

**Comment by juha-h** [comment] 2019-05-30 06:54
Licaon_Kter writes:

> I've called several times, from both devices, nothing happened, not
> even the initial connection, restarted the app on both.
> 
> Then it worked, picked up, pressed the button.
> 
> Do note that on AOSP9 even if nothing works, nooice/zrtp, the info
> shows time connected and opus and stuff. 
> 
> The log had all these and I've tried (and failed I guess) to keep only
> the last call.

I'm a bit lost. Does info button now work (gives call info or tells that
no info is available) using the latest master?

If so, lets close this issue.  You can then open new issues regarding
other problems.

I just tested on my three devices and on all both info and zrtp works
ok.

**Comment by licaon-kter** [comment] 2019-05-30 07:10
Samsung 6.0.1
```
Call Info
No info available.
```

AOSP9:
```
Time
Codecs
Speed
etc
```

**Closed** 2019-05-30 07:11 UTC

**Comment by juha-h** [comment] 2019-05-30 07:18
Licaon_Kter writes:

> Samsung 6.0.1
> ```
> Call Info
> No info available.
> ```
> 
> AOSP9:
> ```
> Time
> Codecs
> Speed
> etc
> ```

So "Info button does nothing" has been solved and we can close this one.
