### ISSUE TITLE
Don't want connect on WiFi, also with turn servers

### ISSUE THREAD

**Issue by KORuL** [juha-h/baresip-studio#290] opened 2022-10-03 08:29 UTC
https://user-images.githubusercontent.com/19871487/193533569-bcc1f9da-be84-4844-8e25-3be5c44d2001.mp4

**Comment by juha-h** [comment] 2022-10-03 10:36
Please describe in writing what the issue is.

**Comment by KORuL** [comment] 2022-10-06 06:36
Everything works through the mobile network. Via Wi-fi - no. Although the turn server is registered and available

**Comment by juha-h** [comment] 2022-10-06 07:26
KORuL writes:

> Everything works through the mobile network. Via Wi-fi - no. Although
> the turn server is registered and available.

So nothing works over WiFi or just turn server is not reachable?

Does the issue appear also when WiFi is connected and you start baresip?

**Comment by juha-h** [comment] 2022-10-11 12:18
This issue should now be fixed in baresip version 49.1.2 and baresip+ version 37.1.2.

**Comment by KORuL** [comment] 2022-10-13 16:28
https://github.com/baresip/baresip/commit/c276dcc8c68c513d085e9ce4fee992933731f5a8
This commit did not help!

**Comment by KORuL** [comment] 2022-10-13 16:39
Everything is still!
I also want to note that the application does not work if you accept these two commits! (generally)
https://github.com/baresip/baresip/commit/c276dcc8c68c513d085e9ce4fee992933731f5a8
https://github.com/baresip/baresip/commit/6bcc376d3c83983a66df60b81c504c16a6951294


If I revert them - everything works, but through the mobile network (via wifi, the stream does not go through the turn server)

**Comment by KORuL** [comment] 2022-10-13 16:46
The connection to the turn server is established successfully. Neither video nor audio is streaming through the turn server. It works, checked through other services, the authentication data is correct

**Comment by juha-h** [comment] 2022-10-13 16:54
I just made a call when my Android device is connected to WiFi hotshop and the account has been configured to use turn:
```
stunserver=turn:openrelay.metered.ca:80
stunuser=openrelayproject
stunpass=openrelayproject
medianat=turn
```
The call and audio worked fine:
```
10-13 19:40:55.286  9818  9886 D Baresip Lib: call: alloc with params laddr=192.168.212.225, af=AF_INET, use_rtp=1
10-13 19:40:55.286  9818  9886 D Baresip Lib: turn: session: scheme=turn host='openrelay.metered.ca'
10-13 19:40:55.286  9818  9886 D Baresip Lib:  port=80 proto=UDP
10-13 19:40:55.286  9818  9886 D Baresip Lib: zrtp: New session <1>
10-13 19:40:55.286  9818  9886 D Baresip Lib: call: use_video=0
10-13 19:40:55.286  9818  9886 D Baresip Lib: call: connecting to 'sip:thetestcall@opensips.org'..
10-13 19:40:55.288  2741  5241 I MediaFocusControl: requestAudioFocus() from uid/pid 10291/9818 clientId=android.media.AudioManager@6948d8acom.tutpro.baresip.BaresipService$$ExternalSyntheticLambda3@deed8e callingPack=com.tutpro.baresip req=2 flags=0x0 sdk=33
10-13 19:40:55.289  9818  9818 D Baresip : Audio focus granted
10-13 19:40:55.294  9818  9818 D Baresip : Orig/new 3 volume is 11/11
10-13 19:40:55.297  9818  9818 D Baresip : Orig/new 0 volume is 5/5
10-13 19:40:55.297  9818  9818 D Baresip : Acquiring proximity wake lock
10-13 19:40:55.299  9818  9886 D Baresip Lib: stream: audio: starting mediaenc 'zrtp' (wait_secure=0)
10-13 19:40:55.697  9818  9886 D Baresip Lib: call: media-nat 'turn' established/gathered
10-13 19:40:55.698  9818  9885 D Baresip Lib: ua event (CALL_LOCAL_SDP) offer
...
10-13 19:47:48.606  9818  9886 D Baresip Lib: UDP 192.168.212.225:41518 -> 136.243.23.236:5060
10-13 19:47:48.606  9818  9886 D Baresip Lib: INVITE sip:thetestcall@opensips.org SIP/2.0
...
10-13 19:47:48.606  9818  9886 D Baresip Lib: v=0
10-13 19:47:48.606  9818  9886 D Baresip Lib: o=- 1237227798 19
10-13 19:47:48.606  9818  9886 D Baresip Lib: 59673719 IN IP4 192.168.212.225
10-13 19:47:48.606  9818  9886 D Baresip Lib: s=-
10-13 19:47:48.606  9818  9886 D Baresip Lib: c=IN IP4 192.168.212.225
10-13 19:47:48.606  9818  9886 D Baresip Lib: t=0 0
10-13 19:47:48.606  9818  9886 D Baresip Lib: m=audio 40431 RTP/AVP 96 97 98 9 0 8 101
10-13 19:47:48.606  9818  9886 D Baresip Lib: c=IN IP4 216.39.253.10
...
10-13 19:40:56.238  9818  9886 D Baresip Lib: call: SIP Progress: 100 Giving it a try (/)
10-13 19:40:56.377  9818  9885 D Baresip Lib: ua event (CALL_ANSWERED) sip:thetestcall@opensips.org
...
```
IP address 216.39.253.10 is openrelay.metered.ca's.

So I'm able to reproduce your issue.  Please try with the same medianat configuration and with baresip 49.1.2 installed from F-Droid (when available) or Play Store.

**Comment by juha-h** [comment] 2022-10-19 06:44
Can't reproduce. Closing.

**Closed** 2022-10-19 06:44 UTC

**Comment by KORuL** [comment] 2022-10-19 08:44
Why can't it be played
I play 10 out of 10
How can I help you reproduce?

**Comment by juha-h** [comment] 2022-10-19 15:15
Show debug of the call.
